### ISSUE TITLE
Update to .NET 5

### ISSUE THREAD

**Issue by Christian-Oleson** [naveenalavilli/CleanArchitecture#9]
**Is your feature request related to a problem? Please describe.**
.NET Core 3.1 end of lifes in about a year (3-Dec-2022). 

**Describe the solution you'd like**
Migrate to .NET 5

**Describe alternatives you've considered**
I would be glad to do the update myself

**Comment by naveenalavilli** [comment]
Oh yes, I will get this done over the weekend.

**Comment by Christian-Oleson** [comment]
I went ahead and did this here:
https://github.com/naveenalavilli/CleanArchitecture/pull/10
